# Requires Docker Compose v2.20+ for `include`
# This file declares the shared volumes & network,
# and recursively includes each service's compose.
name: nextcloud-stack

volumes:
  redis_data:
  clamav_db:
  postgres_data:
  collabora_data:
  nextcloud_data:

networks:
  shared_net:
    driver: bridge

include:
  - path: ./redis/docker-compose.yaml
    project_directory: ./redis
    env_file: ./.env

  - path: ./clamav/docker-compose.yaml
    project_directory: ./clamav
    env_file: ./.env

  - path: ./postgres/docker-compose.yaml
    project_directory: ./postgres
    env_file: ./.env

  - path: ./collabora/docker-compose.yaml
    project_directory: ./collabora
    env_file: ./.env

  - path: ./nextcloud/docker-compose.yaml
    project_directory: ./nextcloud
    env_file: ./.env
